/* ===== Daily quotes (shown once a day and in focus mode) ===== */
const QUOTES = [
  { t: "You have power over your mind — not outside events. Realize this, and you will find strength.", s: "Marcus Aurelius, Meditations" },
  { t: "Confine yourself to the present.", s: "Marcus Aurelius, Meditations" },
  { t: "The impediment to action advances action. What stands in the way becomes the way.", s: "Marcus Aurelius, Meditations" },
  { t: "Waste no more time arguing what a good man should be. Be one.", s: "Marcus Aurelius, Meditations" },
  { t: "Never let the future disturb you. You will meet it with the same weapons of reason which today arm you against the present.", s: "Marcus Aurelius, Meditations" },
  { t: "Begin at once to live, and count each separate day as a separate life.", s: "Marcus Aurelius, Meditations" },
  { t: "The soul becomes dyed with the color of its thoughts.", s: "Marcus Aurelius, Meditations" },
  { t: "If it is not right, do not do it; if it is not true, do not say it.", s: "Marcus Aurelius, Meditations" },
  { t: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look there.", s: "Marcus Aurelius, Meditations" },
  { t: "Do every act of your life as though it were the very last act of your life.", s: "Marcus Aurelius, Meditations" },
  { t: "Dig within. Within is the wellspring of Good; and it is always ready to bubble up, if you just dig.", s: "Marcus Aurelius, Meditations" },
  { t: "Perfection of character is this: to live each day as if it were your last.", s: "Marcus Aurelius, Meditations" },
  { t: "It is not that we have a short time to live, but that we waste a lot of it.", s: "Seneca, On the Shortness of Life" },
  { t: "While we are postponing, life speeds by.", s: "Seneca, Letters to Lucilius" },
  { t: "Difficulties strengthen the mind, as labour does the body.", s: "Seneca" },
  { t: "Luck is what happens when preparation meets opportunity.", s: "Seneca" },
  { t: "We suffer more often in imagination than in reality.", s: "Seneca, Letters to Lucilius" },
  { t: "Every new beginning comes from some other beginning's end.", s: "Seneca" },
  { t: "He who is brave is free.", s: "Seneca" },
  { t: "As long as you live, keep learning how to live.", s: "Seneca, Letters to Lucilius" },
  { t: "The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", s: "Seneca, On the Shortness of Life" },
  { t: "No man was ever wise by chance.", s: "Seneca, Letters to Lucilius" },
  { t: "It is quality rather than quantity that matters.", s: "Seneca, Letters to Lucilius" },
  { t: "First say to yourself what you would be; and then do what you have to do.", s: "Epictetus, Discourses" },
  { t: "No man is free who is not master of himself.", s: "Epictetus" },
  { t: "It is impossible for a man to learn what he thinks he already knows.", s: "Epictetus, Discourses" },
  { t: "Don't explain your philosophy. Embody it.", s: "Epictetus" },
  { t: "Make the best use of what is in your power, and take the rest as it happens.", s: "Epictetus, Discourses" },
  { t: "Difficulties are things that show a person what they are.", s: "Epictetus, Discourses" },
  { t: "If you wish to be a writer, write. If you wish to improve, practice.", s: "Epictetus, Discourses" },
  { t: "Circumstances don't make the man, they only reveal him to himself.", s: "Epictetus" },
  { t: "Progress is not achieved by luck or accident, but by working on yourself daily.", s: "Epictetus" },
  { t: "Know, first, who you are; and then adorn yourself accordingly.", s: "Epictetus, Discourses" },
  { t: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", s: "Aristotle (Will Durant, on Aristotle)" },
  { t: "The roots of education are bitter, but the fruit is sweet.", s: "Aristotle" },
  { t: "Knowing yourself is the beginning of all wisdom.", s: "Aristotle" },
  { t: "Excellence is never an accident. It is the result of high intention and intelligent effort.", s: "Aristotle" },
  { t: "Educating the mind without educating the heart is no education at all.", s: "Aristotle" },
  { t: "Patience is bitter, but its fruit is sweet.", s: "Aristotle" },
  { t: "Pleasure in the job puts perfection in the work.", s: "Aristotle" },
  { t: "The beginning is the most important part of the work.", s: "Plato, The Republic" },
  { t: "Do not train children to learning by force and harshness, but lead them by what amuses them.", s: "Plato, The Republic" },
  { t: "An unexamined life is not worth living.", s: "Socrates (Plato, Apology)" },
  { t: "I know that I know nothing.", s: "Socrates (Plato, Apology)" },
  { t: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", s: "attributed to Socrates" },
  { t: "Education is the kindling of a flame, not the filling of a vessel.", s: "attributed to Socrates" },
  { t: "Wonder is the beginning of wisdom.", s: "Socrates (Plato, Theaetetus)" },
  { t: "A journey of a thousand miles begins with a single step.", s: "Lao Tzu, Tao Te Ching" },
  { t: "Mastering others is strength. Mastering yourself is true power.", s: "Lao Tzu, Tao Te Ching" },
  { t: "Nature does not hurry, yet everything is accomplished.", s: "Lao Tzu, Tao Te Ching" },
  { t: "When I let go of what I am, I become what I might be.", s: "Lao Tzu, Tao Te Ching" },
  { t: "It does not matter how slowly you go as long as you do not stop.", s: "Confucius" },
  { t: "The man who moves a mountain begins by carrying away small stones.", s: "Confucius" },
  { t: "Real knowledge is to know the extent of one's ignorance.", s: "Confucius, Analects" },
  { t: "I hear and I forget. I see and I remember. I do and I understand.", s: "Confucius" },
  { t: "Study the past if you would define the future.", s: "Confucius" },
  { t: "Every battle is won before it is ever fought.", s: "Sun Tzu, The Art of War" },
  { t: "In the midst of chaos, there is also opportunity.", s: "Sun Tzu, The Art of War" },
  { t: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", s: "Sun Tzu, The Art of War" },
  { t: "Opportunities multiply as they are seized.", s: "Sun Tzu, The Art of War" },
  { t: "The supreme art of war is to subdue the enemy without fighting.", s: "Sun Tzu, The Art of War" },
  { t: "Today is victory over yourself of yesterday.", s: "Miyamoto Musashi, The Book of Five Rings" },
  { t: "Do nothing which is of no use.", s: "Miyamoto Musashi, The Book of Five Rings" },
  { t: "Perceive that which cannot be seen with the eye.", s: "Miyamoto Musashi, The Book of Five Rings" },
  { t: "You must understand that there is more than one path to the top of the mountain.", s: "Miyamoto Musashi" },
  { t: "The primary thing when you take a sword in your hands is your intention to cut the enemy.", s: "Miyamoto Musashi, The Book of Five Rings" },
  { t: "From one thing, know ten thousand things.", s: "Miyamoto Musashi, The Book of Five Rings" },
  { t: "Chess is the struggle against the error.", s: "Johannes Zukertort" },
  { t: "The blunders are all there on the board, waiting to be made.", s: "Savielly Tartakower" },
  { t: "Tactics flow from a superior position.", s: "Bobby Fischer" },
  { t: "You must take your opponent into a deep dark forest where 2+2=5.", s: "Mikhail Tal" },
  { t: "Chess is 99 percent tactics.", s: "Richard Teichmann" },
  { t: "Excellence at chess is one mark of a scheming mind.", s: "Arthur Conan Doyle, A Study in Scarlet" },
  { t: "When you see a good move, look for a better one.", s: "Emanuel Lasker" },
  { t: "The hardest game to win is a won game.", s: "Emanuel Lasker" },
  { t: "On the chessboard, lies and hypocrisy do not survive long.", s: "Emanuel Lasker" },
  { t: "A bad plan is better than none at all.", s: "Frank Marshall" },
  { t: "Help your pieces so they can help you.", s: "Paul Morphy" },
  { t: "Every chess master was once a beginner.", s: "Irving Chernev" },
  { t: "Method is more important than strength.", s: "Aaron Nimzowitsch, My System" },
  { t: "The threat is stronger than the execution.", s: "Aaron Nimzowitsch, My System" },
  { t: "First restrain, next blockade, lastly destroy.", s: "Aaron Nimzowitsch, My System" },
  { t: "Chess is the gymnasium of the mind.", s: "attributed to Blaise Pascal" },
  { t: "In life, as in chess, forethought wins.", s: "Charles Buxton" },
  { t: "Play the opening like a book, the middlegame like a magician, and the endgame like a machine.", s: "Rudolf Spielmann" },
  { t: "Nobody ever won a chess game by resigning.", s: "Savielly Tartakower" },
  { t: "Chess, like love, like music, has the power to make men happy.", s: "Siegbert Tarrasch" },
  { t: "Before the endgame, the gods have placed the middlegame.", s: "Siegbert Tarrasch" },
  { t: "One doesn't have to play well, it's enough to play better than your opponent.", s: "Siegbert Tarrasch" },
  { t: "An investment in knowledge pays the best interest.", s: "Benjamin Franklin" },
  { t: "Energy and persistence conquer all things.", s: "Benjamin Franklin" },
  { t: "Well done is better than well said.", s: "Benjamin Franklin" },
  { t: "Genius is one percent inspiration and ninety-nine percent perspiration.", s: "Thomas Edison" },
  { t: "I have not failed. I've just found 10,000 ways that won't work.", s: "Thomas Edison" },
  { t: "It's not that I'm so smart, it's just that I stay with problems longer.", s: "Albert Einstein" },
  { t: "Anyone who has never made a mistake has never tried anything new.", s: "Albert Einstein" },
  { t: "The only source of knowledge is experience.", s: "Albert Einstein" },
  { t: "Discipline is the bridge between goals and accomplishment.", s: "Jim Rohn" },
  { t: "Success is nothing more than a few simple disciplines, practiced every day.", s: "Jim Rohn" },
  { t: "We must all suffer one of two things: the pain of discipline or the pain of regret.", s: "Jim Rohn" },
  { t: "He who has a why to live can bear almost any how.", s: "Friedrich Nietzsche, Twilight of the Idols" },
  { t: "That which does not kill us makes us stronger.", s: "Friedrich Nietzsche, Twilight of the Idols" },
  { t: "The doer alone learneth.", s: "Friedrich Nietzsche, Thus Spoke Zarathustra" },
  { t: "Fall seven times, stand up eight.", s: "Japanese proverb" },
  { t: "Vision without action is a daydream. Action without vision is a nightmare.", s: "Japanese proverb" },
  { t: "The expert in anything was once a beginner.", s: "Helen Hayes" },
  { t: "Practice isn't the thing you do once you're good. It's the thing you do that makes you good.", s: "Malcolm Gladwell, Outliers" },
  { t: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", s: "Winston Churchill" },
  { t: "Success is not final, failure is not fatal: it is the courage to continue that counts.", s: "attributed to Winston Churchill" },
  { t: "Quality is not an act, it is a habit.", s: "Aristotle (Will Durant, The Story of Philosophy)" },
  { t: "The best way out is always through.", s: "Robert Frost, A Servant to Servants" },
  { t: "Do not go where the path may lead, go instead where there is no path and leave a trail.", s: "Ralph Waldo Emerson" },
  { t: "The mind is everything. What you think you become.", s: "attributed to the Buddha" },
  { t: "Drop by drop is the water pot filled.", s: "The Dhammapada" },
  { t: "Irrigators channel waters; fletchers straighten arrows; carpenters bend wood; the wise master themselves.", s: "The Dhammapada" },
  { t: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", s: "attributed to Goethe" },
  { t: "Knowing is not enough; we must apply. Willing is not enough; we must do.", s: "Johann Wolfgang von Goethe" },
  { t: "He who has begun has half done. Dare to be wise; begin!", s: "Horace, Epistles" },
  { t: "Seize the day, put very little trust in tomorrow.", s: "Horace, Odes" },
  { t: "Fortune favours the bold.", s: "Virgil, Aeneid" },
  { t: "Perseverance, secret of all triumphs.", s: "Victor Hugo" },
  { t: "Little strokes fell great oaks.", s: "Benjamin Franklin, Poor Richard's Almanack" },
  { t: "Nothing in the world can take the place of persistence.", s: "Calvin Coolidge" },
  { t: "What we learn with pleasure we never forget.", s: "Alfred Mercier" },
  { t: "Learning never exhausts the mind.", s: "Leonardo da Vinci" },
  { t: "Obstacles cannot crush me; every obstacle yields to stern resolve.", s: "Leonardo da Vinci" },
  { t: "Simplicity is the ultimate sophistication.", s: "attributed to Leonardo da Vinci" },
  { t: "It is not enough to have a good mind; the main thing is to use it well.", s: "René Descartes, Discourse on the Method" },
  { t: "Each problem that I solved became a rule which served afterwards to solve other problems.", s: "René Descartes, Discourse on the Method" },
  { t: "Reading maketh a full man; conference a ready man; and writing an exact man.", s: "Francis Bacon, Of Studies" },
  { t: "Knowledge is power.", s: "Francis Bacon" },
  { t: "Studies serve for delight, for ornament, and for ability.", s: "Francis Bacon, Of Studies" },
  { t: "There is no royal road to geometry.", s: "Euclid, to Ptolemy I" },
  { t: "Give me a place to stand, and I shall move the earth.", s: "Archimedes" },
  { t: "Well begun is half done.", s: "Greek proverb (cited by Aristotle)" },
  { t: "By failing to prepare, you are preparing to fail.", s: "attributed to Benjamin Franklin" },
  { t: "The will to win is nothing without the will to prepare.", s: "Juma Ikangaa" },
  { t: "Champions keep playing until they get it right.", s: "Billie Jean King" },
  { t: "You miss 100% of the shots you don't take.", s: "Wayne Gretzky" },
  { t: "Hard work beats talent when talent doesn't work hard.", s: "Tim Notke" },
  { t: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", s: "Stephen King, On Writing" },
  { t: "The secret of getting ahead is getting started.", s: "attributed to Mark Twain" },
  { t: "Concentrate all your thoughts upon the work in hand.", s: "Alexander Graham Bell" },
  { t: "Great things are done by a series of small things brought together.", s: "Vincent van Gogh" },
  { t: "If I have seen further, it is by standing on the shoulders of giants.", s: "Isaac Newton" },
  { t: "Truth is ever to be found in simplicity.", s: "Isaac Newton" },
  { t: "Errors using inadequate data are much less than those using no data at all.", s: "Charles Babbage" },
  { t: "The more I practice, the luckier I get.", s: "attributed to Gary Player" },
  { t: "A ship in harbor is safe, but that is not what ships are built for.", s: "John A. Shedd" },
  { t: "Courage is going from failure to failure without losing enthusiasm.", s: "attributed to Winston Churchill" },
  { t: "There are no shortcuts to any place worth going.", s: "Beverly Sills" },
  { t: "What you get by achieving your goals is not as important as what you become by achieving them.", s: "attributed to Henry David Thoreau" },
  { t: "Go confidently in the direction of your dreams.", s: "Henry David Thoreau, Walden" },
  { t: "It is not enough to be busy. The question is: what are we busy about?", s: "Henry David Thoreau" },
  { t: "Attention is the rarest and purest form of generosity.", s: "Simone Weil" },
  { t: "The faculty of voluntarily bringing back a wandering attention is the very root of judgement, character and will.", s: "William James, The Principles of Psychology" },
  { t: "Chess is life.", s: "Bobby Fischer" },
  { t: "All that matters on the chessboard is good moves.", s: "Bobby Fischer" },
  { t: "I don't believe in psychology. I believe in good moves.", s: "Bobby Fischer" },
  { t: "Chess demands total concentration.", s: "Bobby Fischer" },
  { t: "You have to have the fighting spirit. You have to force moves and take chances.", s: "Bobby Fischer" },
  { t: "Chess is a matter of vanity.", s: "Garry Kasparov" },
  { t: "The highest art of the chess player lies in not allowing your opponent to show you what he can do.", s: "Garry Kasparov" },
  { t: "Chess is mental torture.", s: "Garry Kasparov" },
  { t: "Hard work is a talent.", s: "Magnus Carlsen" },
  { t: "I am trying to beat the guy sitting across from me and trying to choose the moves that are most unpleasant for him.", s: "Magnus Carlsen" },
  { t: "Without the element of enjoyment, it is not worth trying to excel at anything.", s: "Magnus Carlsen" },
  { t: "Chess is above all a fight.", s: "Emanuel Lasker" },
  { t: "A chess game is divided into three stages: the one when you hope you have the advantage, the second when you believe you have an advantage, and the third when you know you're going to lose.", s: "Savielly Tartakower" },
  { t: "Chess is a fairy tale of 1001 blunders.", s: "Savielly Tartakower" },
  { t: "Even a poor plan is better than no plan at all.", s: "Mikhail Chigorin" },
  { t: "The pin is mightier than the sword.", s: "Fred Reinfeld" },
  { t: "Life is like a game of chess, changing with each move.", s: "Chinese proverb" },
  { t: "Chess is imagination.", s: "David Bronstein" },
  { t: "Attack! Always attack!", s: "Adolf Anderssen" },
  { t: "Only the player with the initiative has the right to attack.", s: "Wilhelm Steinitz" },
  { t: "A win by an unsound combination, however showy, fills me with artistic horror.", s: "Wilhelm Steinitz" },
  { t: "Talent is 1 percent; work is 99 percent.", s: "Mikhail Botvinnik" },
  { t: "Chess is the art of analysis.", s: "Mikhail Botvinnik" },
  { t: "Chess is no whit inferior to the violin, and we have a plethora of great violinists.", s: "Mikhail Botvinnik" },
  { t: "The winner of the game is the player who makes the next-to-last mistake.", s: "Savielly Tartakower" },
  { t: "Strategy requires thought; tactics require observation.", s: "Max Euwe" },
  { t: "Nothing excites jaded Grandmasters more than a theoretical novelty.", s: "Dominic Lawson" },
  { t: "Chess holds its master in its own bonds, shackling the mind and brain so that the inner freedom of the very strongest must suffer.", s: "Albert Einstein" },
  { t: "To avoid losing a piece, many a person has lost the game.", s: "Savielly Tartakower" },
  { t: "Discovered check is the dive-bomber of the chessboard.", s: "Reuben Fine" },
  { t: "The passed pawn is a criminal, who should be kept under lock and key.", s: "Aaron Nimzowitsch" },
  { t: "Chess makes men wiser and clear-sighted.", s: "Vladimir Putin's chess coach, quoted in the Soviet school" },
  { t: "When in doubt, play chess!", s: "Tevis, The Queen's Gambit" },
  { t: "Study the endgame before everything else.", s: "Jose Raul Capablanca" },
  { t: "In order to improve your game, you must study the endgame before everything else.", s: "Jose Raul Capablanca" },
  { t: "You may learn much more from a game you lose than from a game you win.", s: "Jose Raul Capablanca" },
  { t: "A good player is always lucky.", s: "Jose Raul Capablanca" },
  { t: "I have added these principles to the law: get the knights into action before both bishops are developed.", s: "Emanuel Lasker" },
  { t: "Chess, like any creative activity, can exist only through the combined efforts of those who have creative talent.", s: "Mikhail Botvinnik" },
  { t: "Every pawn is a potential queen.", s: "James Mason" },
];

/* Deterministic pick: the same quote for the whole day, a different one each day. */
function quoteOfDay(key = todayKey(), salt = 0) {
  let hnum = 2166136261;
  const src = key + '|' + salt;
  for (let i = 0; i < src.length; i++) { hnum ^= src.charCodeAt(i); hnum = Math.imul(hnum, 16777619); }
  return QUOTES[Math.abs(hnum) % QUOTES.length];
}
function randomQuote() { return QUOTES[Math.floor(Math.random() * QUOTES.length)]; }
